baseURL = "https://antoinelemarchand.xyz"
title = "Antoine Lemarchand"

[module]
	[module.hugoVersion]
		extended = true

[menu]
	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/about"
		weight = 1

	[[menu.main]]
		identifier = "projects"
		name = "Projects"
		url = "/projects"
		weight = 2

	[[menu.main]]
		identifier = "post"
		name = "Blog"
		url = "/posts"
		weight = 3

	[[menu.main]]
		identifier = "contact"
		name = "Contact"
		url = "/contact"
		weight = 4

[taxonomies]
	category = "categories"
	series = "series"
	tag = "tags"
	author = "authors"

[[params.social]]
	name = "Git"
	icon = "Git.svg"
	weight = 1
	url = "https://github.com/antoinelemarchand/"

[[params.social]]
	name = "LinkedIn"
	icon = "LinkedIn.svg"
	weight = 4
	url = "https://www.linkedin.com/in/antoine-lemarchand-334526162/"

[[params.project]]
	name = "fract-ol"
	weight = 2

[[params.project]]
	name = "minishell"
	weight = 2

[[params.project]]
	name = "minirt"
	weight = 2

[[params.project]]
	name = "ft_irc"
	weight = 2
